#!/usr/bin/env bash
# Displays numbers from 1 to 20 and a message after the unlucky ones
i=1
while [ $i -le 20 ]
do
  echo "$i"
  case $i in
    4) echo "bad luck from China" ;;
    9) echo "bad luck from Japan" ;;
    17) echo "bad luck from Italy" ;;
  esac
  i=$((i + 1))
done
