#!/usr/bin/env bash
# Init script that starts, stops and restarts manage_my_process
dir="$(dirname "$0")"
case "$1" in
  start)
    "$dir/manage_my_process" > /dev/null 2>&1 &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    kill "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    kill "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
    "$dir/manage_my_process" > /dev/null 2>&1 &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
